### ISSUE TITLE
Logo Proposal for Partyfy

### ISSUE THREAD

**Issue by area55git** [SamuelWitke/Partify#2]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project "Partify".

I will be pleased to collaborate with you.

**Comment by SamuelWitke** [comment]
Hey, that sounds fantastic I have no experience in graphic design so any submission for a logo will definitely be used. The only thing is Spotify does not allow ```... Brand Features whether for commercial or non-commercial use.``` according to [Legal](https://www.spotify.com/us/legal/end-user-agreement/) so it would have to be unique. But when you are ready submit a pull request I will merge it into master.

**Comment by area55git** [comment]
Perfect, I will start working on it, do you have any condition or suggestion?

**Comment by SamuelWitke** [comment]
I mean nothing blatantly offensive or trademarked, so feel free to get as creative as you want.

**Comment by SamuelWitke** [comment]
Just according to the title of the repo the spelling is Partify.
